# Fix escape key lag in Vim.
set -s escape-time 0

# Vim "vsp" alias.
set -s command-alias[10] vsp='split-window -h'

# Vim keybindings for copy mode.
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# Vim keybindings for navigating panes.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'mshkrebtan/base16-tmux'

run '~/.tmux/plugins/tpm/tpm'
